###### To solve a puzzle, you are given an initial state and a goal state.
###### Target is to reach goal state from initial state using puzzle rules.
######  We can move blank tile only on left, right, up, and down
![Capture.JPG](attachment:Capture.JPG)

# Generate an intial state of NPuzzle

In [1]:
import numpy as np
import random
import math

In [158]:
def get_state():
    N = random.choice([3,4,5])
    state = [item for item in range(N*N)]# [0,1,2,...,15]
    random.shuffle(state)
    tmp = np.array(state)
    print(tmp.reshape(N,N))
    return state

In [15]:
def get_dim(s):
  return int(math.sqrt(len(s)))

In [133]:
s = get_state()
print(s)
print('Dimension:', get_dim(s))

[[1 4 7]
 [3 6 8]
 [2 5 0]]
[1, 4, 7, 3, 6, 8, 2, 5, 0]
Dimension: 3


# Calculate inversion

Inversion is a pair of tiles that are in the reverse order from where they ought to be. In our case, the bigger number is in front of the smaller one.



![Capture.JPG](attachment:Capture.JPG)

In [5]:
def get_invCount(s):
    count = 0
    for i in range(len(s)):
        for j in range(i+1,len(s)):
            if s[j]!=0 and s[i] > s[j]: count += 1
    return count

In [178]:
s = get_state()
print(s)
print(get_invCount(s))

[[ 2 17  4  9  8]
 [ 3 24 18 10 15]
 [12 19  0 20  6]
 [14 22 21  7 16]
 [ 1 11  5 13 23]]
[2, 17, 4, 9, 8, 3, 24, 18, 10, 15, 12, 19, 0, 20, 6, 14, 22, 21, 7, 16, 1, 11, 5, 13, 23]
118


In [119]:
s.index(0)

16

In [139]:
get_invCount(s)

19

# **Find blank row**

In [106]:
# find row position of the blank tile
def get_blank_row(s):
  n = get_dim(s)
  return n - math.floor(s.index(0) / n)

In [179]:
get_blank_row(s)

3

# Solvability Rules

In [127]:
# apply the rules to decide solvability
#  N, I, R
# define a method to return solvability (input S)
# return True if solvable or False if not

def isSolvable(state):
  D = get_dim(state)
  I = get_invCount(state)
  R = get_blank_row(state)

  if (D%2==1 and I%2==0) or (D%2==0 and R%2==1 and I%2==0) or (D%2==0 and R%2==0 and I%2==1):
    return True
  else:
    return False


In [167]:
#s = get_state()
isSolvable(s)

True

In [173]:
s = get_state()
isSolvable(s)

[[ 2  4  7 11]
 [ 0 14  1 10]
 [ 9  5  8 15]
 [12 13  6  3]]


True

In [174]:
s = get_state()
print()
while(isSolvable(s)==False):
  s = get_state()
  print()
print("Solvable problem: ", s)

[[ 1 10  0 19 17]
 [24 21  8 16  6]
 [22  5 23 15  2]
 [ 9 18  3 14 11]
 [ 7 20 13  4 12]]

[[1 3 7]
 [2 4 6]
 [5 0 8]]

Solvable problem:  [1, 3, 7, 2, 4, 6, 5, 0, 8]
